default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/lasuillard/pre-commit-hooks
    rev: v0.2.1
    hooks:
      - id: check-directory-structure
        args: [--source, django_slack_tools, --extend-exclude, '**/migrations/*.py']

  - repo: local
    hooks:
      - id: django-migration
        name: Check migrations created for model changes
        language: system
        types: [python]
        pass_filenames: false
        entry: poetry run python manage.py makemigrations
        args: [--check, --dry-run]

      - id: ruff
        name: Fix using Ruff
        language: system
        types: [python]
        entry: poetry run ruff

      - id: black
        name: Format with Black
        language: system
        types: [python]
        entry: poetry run black --config ./pyproject.toml

      - id: mypy
        name: Type check with Mypy
        language: system
        types: [python]
        pass_filenames: false
        entry: poetry run mypy
        args: [--show-error-codes, --pretty, .]

      - id: pytest
        name: Test with pytest
        language: system
        types: [python]
        pass_filenames: false
        entry: poetry run pytest

ci:
  autoupdate_schedule:  quarterly
