version: "3"

services:
  workspace:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: workspace
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${NGROK_HOST:-127.0.0.1}:${NGROK_PORT:-4040}:4040  # ngrok inspect UI
      - ${DJANGO_HOST:-127.0.0.1}:${DJANGO_PORT:-8000}:8000
    environment:
      CONTAINER: 1
    command: sleep infinity
    init: true
