[tool.poetry]
name = "todo"
version = "0.1.0"
description = "Example To-Do Slack bot application."
authors = ["Yuchan Lee <lasuillard@gmail.com>"]
license = "MIT"
readme = "README.md"
classifiers = ["Private :: Do not Upload"]

[tool.poetry.dependencies]
python = "^3.8"
django-slack-bot = { git = "https://github.com/lasuillard/django-slack-bot.git", rev = "4da8e0c" } # FIXME(lasuillard): No release yet

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
