name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Poetry
        run: pip install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: poetry
          cache-dependency-path: pyproject.toml

      - name: Install pip deps
        run: poetry install

      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: pytest

      - uses: pre-commit-ci/lite-action@v1.0.2
        if: always()

  test:
    name: Test (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        django-version: ["3.2", "4.2"]
        include:
          - python-version: "3.11"
            django-version: "4.2"

          - python-version: "3.12"
            django-version: "4.2"

          - python-version: "3.10"
            django-version: "5.0"

          - python-version: "3.11"
            django-version: "5.0"

          - python-version: "3.12"
            django-version: "5.0"

          - python-version: "3.10"
            django-version: "5.1"

          - python-version: "3.11"
            django-version: "5.1"

          - python-version: "3.12"
            django-version: "5.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Poetry
        run: pip install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: pyproject.toml

      - name: Install pip deps
        run: poetry install

      - name: Install Django
        run: poetry run pip install Django=="${{ matrix.django-version }}.*"

      - name: Run tests
        run: poetry run pytest

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        env:
          PYTHON: ${{ matrix.python-version }}
          DJANGO: ${{ matrix.django-version }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: coverage.xml
          env_vars: PYTHON,DJANGO
