name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_FROZEN: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: latest
          enable-cache: true

      - name: Install deps
        run: uv sync

      - name: Check code formatting
        run: uv run ruff format --check .

      - name: Lint code
        run: uv run ruff check .

      - name: Type check
        run: uv run mypy --show-error-codes --pretty .

      - name: Check migrations
        run: uv run python manage.py makemigrations --check --dry-run

  test:
    name: Test (py${{ matrix.python-version }}, django${{ matrix.django-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        django-version: ["5.2"]

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: latest
          enable-cache: true

      - name: Override Python version
        run: uv python pin "${{ matrix.python-version }}"

      - name: Install deps
        run: uv sync

      - name: Install Django
        run: uv pip install Django=="${{ matrix.django-version }}.*"

      - name: Run tests
        run: uv run nox

      - name: Upload test results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          fail_ci_if_error: false
          report_type: test_results
          files: junit.xml
          flags: >-
            python-${{ matrix.python-version }},
            django-${{ matrix.django-version }}

      - name: Upload coverage report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        env:
          PYTHON: ${{ matrix.python-version }}
          DJANGO: ${{ matrix.django-version }}
        with:
          use_oidc: true
          fail_ci_if_error: false
          files: coverage.xml
          env_vars: PYTHON,DJANGO
          flags: >-
            python-${{ matrix.python-version }},
            django-${{ matrix.django-version }}
