name: Docs

on:
  release:
    types: [published]

permissions: read-all

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Poetry
        run: pip install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: poetry
          cache-dependency-path: pyproject.toml

      - name: Install pip deps
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Generate API docs
        run: make docs

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy-docs:
    name: Deploy Docs
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Publish API docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
